"""initial tables

Revision ID: 0001
Revises:
Create Date: 2026-10-06 05:39:31.556910
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=20), nullable=False),
        sa.Column("item_key", sa.String(length=300), nullable=False),
        sa.Column("client", sa.String(length=100), nullable=True),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ladder_step", sa.Integer(), nullable=False),
        sa.Column("last_sent_at", sa.JSON(), nullable=False),
        sa.Column("sends_count", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_item_key"), ["item_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_state"), ["state"], unique=False)

    op.create_table(
        "digest_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(length=200), nullable=False),
        sa.Column("rule_id", sa.String(length=20), nullable=False),
        sa.Column("item_key", sa.String(length=300), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("digest_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_digest_items_user"), ["user"], unique=False)

    op.create_table(
        "kill_switches",
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("on", sa.Boolean(), nullable=False),
        sa.Column("set_by", sa.String(length=200), nullable=False),
        sa.Column("set_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("scope", "key"),
    )
    op.create_table(
        "question_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("idk", sa.Boolean(), nullable=False),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_question_log_user"), ["user"], unique=False)

    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("recipient", sa.String(length=200), nullable=True),
        sa.Column("rule_id", sa.String(length=20), nullable=True),
        sa.Column("action_type", sa.String(length=20), nullable=False),
        sa.Column("delivery", sa.String(length=20), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("item_key", sa.String(length=300), nullable=True),
        sa.Column("deliver_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_receipts_item_key"), ["item_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_receipts_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_receipts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_receipts_time"), ["time"], unique=False)

    op.create_table(
        "review_marks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("verdict", sa.String(length=10), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_marks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_marks_alert_id"), ["alert_id"], unique=False)

    op.create_table(
        "rule_state",
        sa.Column("rule_id", sa.String(length=20), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=True),
        sa.Column("phase_reason", sa.Text(), nullable=True),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=200), nullable=False),
        sa.Column("user", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_turns_conversation_id"), ["conversation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turns_conversation_id"))

    op.drop_table("turns")
    op.drop_table("rule_state")
    with op.batch_alter_table("review_marks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_marks_alert_id"))

    op.drop_table("review_marks")
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_receipts_time"))
        batch_op.drop_index(batch_op.f("ix_receipts_status"))
        batch_op.drop_index(batch_op.f("ix_receipts_rule_id"))
        batch_op.drop_index(batch_op.f("ix_receipts_item_key"))

    op.drop_table("receipts")
    with op.batch_alter_table("question_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_log_user"))

    op.drop_table("question_log")
    op.drop_table("kill_switches")
    with op.batch_alter_table("digest_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_digest_items_user"))

    op.drop_table("digest_items")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_state"))
        batch_op.drop_index(batch_op.f("ix_alerts_rule_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_item_key"))

    op.drop_table("alerts")
    # ### end Alembic commands ###
