"""rule_state phase_changed_at

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 05:55:50.588574
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule_state", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("phase_changed_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule_state", schema=None) as batch_op:
        batch_op.drop_column("phase_changed_at")

    # ### end Alembic commands ###
